### ISSUE TITLE
Environment variable $HOME not working for logger destination

### ISSUE THREAD

**Issue by Wolfsrudel** [cloud66-oss/trackman#11]
If i try using
```
logger:                                                                                                                                                                                                                           
  type: "file"                                                                                                                                                                                                                    
    format: "json"                                                                                                                                                                                                                  
    destination: "${HOME}/workspace/logfiles/trackman/{{ if .Step }}{{.Step.Name}}{{ else }}workflow{{ end }}.json"
```
it exits with
```
open ${HOME}/workspace/logfiles/trackman/workflow.json: no such file or directory
```
Is `$HOME` only available for `workdir` and `command`?
