### ISSUE TITLE
Metadata not available in workdir stanza

### ISSUE THREAD

**Issue by Wolfsrudel** [cloud66-oss/trackman#12]
If i try using
```
[...]
metadata:                                                                                                                                                                                                                         
  repository_home_local: "${HOME}/workspace/repository/internal"
steps:                                                                                                                                                                                                                            
  - name: "sync.repo-puppet"                                                                                                                                                                                                      
      workdir: {{ index .Metdata \"repository_home_local\" }}/myrepot"                                                                                                                                                            
      command: "./pull-all.sh"                                                                                                                                                                                                      
      timeout: "120s"
```
trackman exists with
```
{"Step":"sync.repo-puppet","level":"error","msg":"chdir {{ index .Metadata \"repository_home_local\" }}/myrepo: no such file or directory","time":"2020-02-07T08:30:53+01:00"}

```
Is this intended or not implemented?
