### ISSUE TITLE
Define metadata with template key

### ISSUE THREAD

**Issue by Wolfsrudel** [cloud66-oss/trackman#14]
Is it possible to use the following code?
```
metadata:
  repository_home_internal: "${HOME}/workspace/repository/internal"
  repository_home_internal_common: "{{ index .Metdata \"repository_home_internal\" }}/common"
  repository_home_internal_specific: "{{ index .Metdata \"repository_home_internal\" }}/specific"
```
It should be like defining a variable with a pre-defined variable content.
