### ISSUE TITLE
any $param in command are getting replaced

### ISSUE THREAD

**Issue by santhosh60** [cloud66-oss/trackman#16]
any $name is getting replaced with an environment variable, which leads to unexpected results as in the awk example below

### input
```yaml
version: 1
steps:
  - name: awk issue
    metadata:
        filename: sample.tsv
    command:  echo "Hello World!" | awk  '{print $1}'
```

### parsed output
```
version: "1"
metadata: {}
steps:
- metadata:
    filename: sample.tsv
  name: awk issue
  command: echo "Hello World!" | awk  '{print }'
  continue_on_fail: false
  timeout: null
  workdir: ""
  env: []
  probe: null
  depends_on: []
  preflights: []
  ask_to_proceed: false
  show_command: false
  disabled: false
  logger: null
logger: null
```

### expected
```
echo "Hello World!" | awk  '{print $1}'
```
