### ISSUE TITLE
continue_on_failure doesnt work as expected

### ISSUE THREAD

**Issue by santhosh60** [cloud66-oss/trackman#4]
In the below example expecting step 'hello' to run even when step 'timeout' failes, but the step fails.
find the details below:

##### input:
```yaml
version: 1
steps:
  - name: hello
    command: echo "Hello, World!"
    depends_on:
      - timeout
  - name: timeout
    command: sleep 20
    timeout: 10s
    continue_on_failure: true
```
##### output:
INFO[0000] Running Preflight checks
INFO[0000] Preflight checks complete
INFO[0000] Starting                                      Step=timeout
DEBU[0000] Running                                       Step=timeout
ERRO[0010] Timed out                                     Step=timeout
ERRO[0010] step timeout timed out after 10s              Step=timeout
ERRO[0010] Calling a stop to run                         Step=timeout
INFO[0010] Starting                                      Step=hello
ERRO[0010] Done with errors
